### ISSUE TITLE
[BUG]查询别名时返回类型错误

### ISSUE THREAD

**Issue by yaowan233** [SEAFHMC/nonebot-plugin-arcaeabot#12]
使用指令
/arc best αterlβus
时报错
```bash
05-13 18:43:16 [ERROR] nonebot | Running matcher <Matcher from miyuki.plugins.nonebot_plugin_arcaeabot.matcher, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "e:\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "e:\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\anaconda3\lib\site-packages\click\core.py", line 754, ininvoke
    return __callback(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "e:\anaconda3\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "e:\anaconda3\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "e:\anaconda3\lib\site-packages\nonebot\drivers\fastapi.py",line 168, in run
    uvicorn.run(
  File "e:\anaconda3\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "e:\anaconda3\lib\site-packages\uvicorn\server.py", line 60,in run
    return asyncio.run(self.serve(sockets=sockets))
  File "e:\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "e:\anaconda3\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "e:\anaconda3\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "e:\anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "e:\anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "e:\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "e:\anaconda3\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)> File "e:\anaconda3\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "e:\anaconda3\lib\site-packages\nonebot\internal\matcher.py",
 line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "e:\anaconda3\lib\site-packages\nonebot\internal\matcher.py",
 line 635, in simple_run
    await handler(
  File "e:\anaconda3\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\miyuki\plugins\nonebot_plugin_arcaeabot\handlers\best.py",
 line 36, in best_handler
    data = SongAlias(**resp)
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
    raise validation_errorpydantic.error_wrappers.ValidationError: 1 validation error for SongAliascontent -> song_id
  str type expected (type=type_error.str)
```
此时api返回的是
{'status': 0, 'content': {'song_id': ['aterlbus'], 'alias': ['黑白之战']}}
song_id是列表类型

**Comment by SEAFHMC** [comment]
api那里不小心搞错了，用全名查询的话会返回列表。
已修复，不需要更新插件。
